name: Deploy HTML from Private Repo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public repo
        uses: actions/checkout@v2

      - name: Checkout private repo
        uses: actions/checkout@v2
        with:
          repository: Kaam-Editing/Kaam-Editing-portfolio-design
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: Kaam-Editing-portfolio-design

      - name: Copy HTML file
        run: |
          # Copy the HTML file to the public directory
          cp Kaam-Editing-portfolio-design/index.html public/

      - name: Deploy to GitHub Pages (or another hosting service)
        run: |
          echo "Deploying to GitHub Pages..."
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add public/index.html
          git commit -m "Deploy HTML from private repo"
          git push origin gh-pages  # Push to a `gh-pages` branch
